# This is an example config file for zelbar-river.
#
# If you want to modify it you should copy it to:
# $XDG_CONFIG_HOME/zelbar-river/config.ini
#
# For more information see zelbar-river(1) man page.

# 0: Left 1: Center 2: Right
alignment = 0;
only_active = true;
tags_amount = 9;
overline = 0;
underline = 0;

background_color = "0x00000000";
foreground_color = "0x202325";
overline_color = "0x00000000";
underline_color = "0x00000000";

focused_background_color = "0x2366da";
focused_foreground_color = "0xf9f9fa";
focused_overline_color = "0x2366da";
focused_underline_color = "0x2366da";

occupied_background_color = "0xdce1e4";
occupied_foreground_color = "0x202325";
occupied_overline_color = "0xdce1e4";
occupied_underline_color = "0xdce1e4";

urgent_background_color = "0xfde7f6";
urgent_foreground_color = "0x202325";
urgent_overline_color = "0xfde7f6";
urgent_underline_color = "0xfde7f6";
