#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# Super+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)

TILER=rivercarro
TILER_EXE=$HOME/.local/bin/rivercarro
TILER_ARGS='-inner-gaps 0 -outer-gaps 0 -main-ratio 0.5 -per-tag'

# TILER=rivercarro
# TILER_EXE=$HOME/opt/rivercarro-0.3.0/bin/rivercarro
# TILER_ARGS='-inner-gaps 0 -outer-gaps 0 -main-ratio 0.5'
rmn() {
    # -layout 0 means to always use EN layout when figuring out if I pressed a
    # given key
    riverctl map -layout 0 normal "$@"
}

rmn Super+Shift Return spawn foot

rmn Super+Shift C close

# Super+Shift+E to exit river
rmn Super+Shift Q exit

# Super+J and Super+K to focus the next/previous view in the layout stack
rmn Super J focus-view next
rmn Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
rmn Super+Shift J swap next
rmn Super+Shift Cyrillic_shorti swap next
rmn Super+Shift K swap previous

# Super+Return to bump the focused view to the top of the layout stack
rmn Super Return zoom

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super+Alt BTN_LEFT resize-view

for i in $(seq 1 14)
do
    tags=$((1 << ($i - 1)))
    if [ $i -le 9 ]; then
        key=$i
    else
        key="F$(($i - 9))"
    fi

    # Super+[1-9] to focus tag [0-8]
    rmn Super $key set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    rmn Super+Shift $key set-view-tags $tags
done

# Super+Space to toggle float
rmn Super T toggle-float

rmn Super Space send-layout-cmd $TILER "main-location-cycle left,monocle"

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
rmn Super H send-layout-cmd $TILER "main-ratio -0.01"
rmn Super L send-layout-cmd $TILER "main-ratio +0.01"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
rmn Super Comma send-layout-cmd $TILER "main-count +1"
rmn Super Period send-layout-cmd $TILER "main-count -1"

rmn Super P spawn 'launcher'

rmn Super+Shift l spawn 'waylock'

rmn Control+Shift 3 spawn '/home/iskren/bin/screenshot'
rmn Control+Shift 4 spawn '/home/iskren/bin/cropscreen'

## Media related
rmn None XF86Eject spawn 'eject -T'

# Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
rmn None XF86AudioRaiseVolume  spawn 'pamixer --allow-boost -i 3'
rmn None XF86AudioLowerVolume  spawn 'pamixer --allow-boost -d 3'
rmn None XF86AudioMute         spawn 'pamixer --toggle-mute'

# Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
rmn None XF86AudioMedia spawn 'playerctl play-pause'
rmn None XF86AudioPlay  spawn 'playerctl play-pause'
rmn None XF86AudioPrev  spawn 'playerctl previous'
rmn None XF86AudioNext  spawn 'playerctl next'

# Control screen backlight brightness with light (https://github.com/haikarainen/light)
rmn None XF86MonBrightnessUp   spawn 'light +5'
rmn None XF86MonBrightnessDown spawn 'light -5'

# TODO(Iskren): Start spotify if not started, here
rmn Super+Shift P spawn 'ensure-spotify; playerctl play-pause'
rmn Super+Shift N  spawn 'playerctl next'
rmn Super+Control R spawn 'pamixer --allow-boost -d 3'
rmn Super+Control T spawn 'pamixer --allow-boost -i 3'
rmn Super+Control F spawn 'light -5'
rmn Super+Control G spawn 'light +5'

riverctl focus-follows-cursor normal

# Set background and border color
riverctl background-color 0x000000
riverctl border-color-focused 0xaa0000
riverctl border-color-unfocused 0x333333
riverctl border-width 1

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make certain views start floating
riverctl float-filter-add app-id float
riverctl float-filter-add title "popup title with spaces"

# Set app-ids and titles of views which should use client side decorations
riverctl csd-filter-add app-id "gedit"

riverctl keyboard-layout  \
    -variant ,phonetic \
    -options grp:alt_shift_toggle,ctrl:nocaps \
    us,bg

TOUCHPAD_DEV=pointer-2362-628-PIXA3854:00_093A:0274_Touchpad

# this enables two-finger click for right mouse button
riverctl input $TOUCHPAD_DEV click-method clickfinger

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.

# riverctl default-layout rivertile
# rivertile -view-padding 0 -outer-padding 0 -main-ratio 0.5 &
riverctl default-layout $TILER

$TILER_EXE $TILER_ARGS &
way-displays > /tmp/way-displays.${XDG_VTNR}.${USER}.log 2>&1 &

# for xdg-desktop-portal-wlr
export XDG_CURRENT_DESKTOP=river
export DISPLAY=:0
systemctl --user import-environment WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP
# restart dropbox with access to DISPLAY=:0 so tray icon will work
systemctl --user restart dropbox.service
dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP

waybar &
# $HOME/.config/bar/full &
nm-applet &
# blueman-applet &
